### ISSUE TITLE
Bitbucket

### ISSUE THREAD

**Issue by cognitus** [gitscrum-team/laravel-gitscrum#229]
@renatomarinho  can you indicate what files are used for oauth (structure)? maybe I can do something...

Bitbucket send this response:
```
User {#391 ▼
  +token: "{token}"
  +refreshToken: "{refreshToken}"
  +expiresIn: 3600
  +id: "{xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}"
  +nickname: "{username}"
  +name: "{name}"
  +email: "{email}"
  +avatar: "https://bitbucket.org/account/{username}/avatar/{id}/"
  +user: array:11 [▼
    "username" => "{username}"
    "website" => "{website}"
    "display_name" => "{name}"
    "account_id" => "557058:xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    "links" => array:8 [▼
      "hooks" => array:1 [▼
        "href" => "https://api.bitbucket.org/2.0/users/{username}/hooks"
      ]
      "self" => array:1 [▶]
      "repositories" => array:1 [▼
        "href" => "https://api.bitbucket.org/2.0/repositories/{username}"
      ]
      "html" => array:1 [▶]
      "followers" => array:1 [▼
        "href" => "https://api.bitbucket.org/2.0/users/{username}/followers"
      ]
      "avatar" => array:1 [▼
        "href" => "https://bitbucket.org/account/{username}/avatar/{id}/"
      ]
      "following" => array:1 [▼
        "href" => "https://api.bitbucket.org/2.0/users/{username}/following"
      ]
      "snippets" => array:1 [▼
        "href" => "https://api.bitbucket.org/2.0/snippets/{username}"
      ]
    ]
    "created_on" => "20xx-xx-xxTxx:33:54.550898+00:00"
    "is_staff" => false
    "location" => null
    "type" => "user"
    "uuid" => "{xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}"
    "email" => "{email}"
  ]
}
```
so we have uuid instead id so i have change the type in DB users.provider_id for accept this type or create a new Column, any ideas?

**Comment by jaredloman** [comment]
@renatomarinho Curious if there is any update on Bitbucket support?

**Comment by cognitus** [comment]
@renatomarinho  any news?

**Comment by renatomarinho** [comment]
Hi @cognitus,

We have integration with Bitbucket (by @Te7a-Houdini ). Have you tried it? Works well?

**Comment by cognitus** [comment]
not, today I installed... it works, but has some bug, for example: 

- not return all repositories from organization 
- icon of github appears en product backlog 
![imagen](https://user-images.githubusercontent.com/2235718/32981988-ba6d0684-cc5b-11e7-9d7a-d16bb016a9cc.png)

**Comment by supermarcos** [comment]
I detected those issues also. I don't find the differences between two of my repos that are, one listed, and the another one don't.... interesting. Also, as @cognitus said, the icon for github is displayed even when these are bitbucket repositories.
